# Generated by Django 4.2 on 2025-07-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_user"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(
                fields=["transaction"], name="payments_ot_transac_5f9308_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(fields=["status"], name="payments_ot_status_d51d92_idx"),
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(
                fields=["expires_at"], name="payments_ot_expires_adc41d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["reference"], name="payments_pa_referen_72073c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["status"], name="payments_pa_status_b6726a_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["created_at"], name="payments_pa_created_a246c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["hubtel_transaction_id"], name="payments_pa_hubtel__828fe7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone"], name="payments_us_phone_9969f6_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="payments_us_email_821cc8_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["account_id"], name="payments_us_account_2808e6_idx"
            ),
        ),
    ]
