# Generated by Django 4.2 on 2025-07-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0003_contactformsubmission"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contactformsubmission",
            index=models.Index(
                fields=["submitted_at"], name="kyc_contact_submitt_3c57ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactformsubmission",
            index=models.Index(
                fields=["is_read"], name="kyc_contact_is_read_fb382e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kycsubmission",
            index=models.Index(fields=["status"], name="kyc_kycsubm_status_1d4f35_idx"),
        ),
        migrations.AddIndex(
            model_name="kycsubmission",
            index=models.Index(
                fields=["submitted_at"], name="kyc_kycsubm_submitt_177b10_idx"
            ),
        ),
    ]
